--Start Writing Table ddls
DROP TABLE STUDENTNEWTABLE;

CREATE TABLE STUDENTNEWTABLE
(
	STUID NUMERIC(9,0)  NOT NULL  ,
	STUDENTID NUMERIC(9,0)  ,
	STUNAME CHARACTER VARYING(256)  ,
	STUCONTACTNO CHARACTER VARYING(256)  ,
	STUADDRESS CHARACTER VARYING(256) ,
	StudentNewTableVer NUMERIC (4, 0)  NOT NULL ,
	dmLastUpdateDate	TIMESTAMP WITH TIME ZONE	NOT NULL  ,
	PRIMARY KEY ( 
	STUID  )
);
DROP TABLE TEACHERNEWTABLE;

CREATE TABLE TEACHERNEWTABLE
(
	TID NUMERIC(9,0)  NOT NULL  ,
	TNAME CHARACTER VARYING(256)  ,
	TCONTACTNO CHARACTER VARYING(256)  ,
	TADDRESS CHARACTER VARYING(256) ,
	TeacherNewTableVer NUMERIC (4, 0)  NOT NULL ,
	dmLastUpdateDate	TIMESTAMP WITH TIME ZONE	NOT NULL  ,
	PRIMARY KEY ( 
	TID  )
);
--End Writing Table ddls
--Start Writing Index ddls
--End Writing Index ddls
--Start Writing Keys ddls
--End Writing Keys ddls
--Start Writing Sequence ddls
--End Writing Sequence ddls
